#------------------------------------------------------------------------------------------#
#                                                                                          #
#    ____       _   _             _____                                          _         #
#   |  _ \     | | | |           / ____|                                        | |        #
#   | |_) | ___| |_| |_ ___ _ __| |     ___  _ __ ___  _ __ ___   __ _ _ __   __| |___     #
#   |  _ < / _ \ __| __/ _ \ '__| |    / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|    #
#   | |_) |  __/ |_| ||  __/ |  | |___| (_) | | | | | | | | | | | (_| | | | | (_| \__ \    #
#   |____/ \___|\__|\__\___|_|   \_____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/    #
#                                                                                          #
#------------------------------------------------------------------------------------------#

# BetterCommands by Norbit4

# github: https://github.com/Norbit4

# If you like the plugin, support me with a positive opinion <3

#---------------------------------------#
#                [Help]                 #
#---------------------------------------#

# 1.Reload config:
#  To reload config use /bc reload, or /bettercommands reload command.

#  [!] When you add a new command or change name existing command, you need to restart the server!
#  Paper server doesn't support add new commands without a restart server :c

# 2.Actions:
#   - replace:
#      replace command to another command
#      ex. /core -> /essentials, when a player uses /core reload it will replace to /essentials reload

#   - text:
#      send a message to player who uses command

#   - broadcast:
#      broadcast message to all players on server

#   - server_command:
#      execute command as console

#   - player_command:
#      execute command as player

# 3.Sub-commands:
#   - You can create sub-commands for main command
#   - To use sub-commands, use /main-command sub-command
#   - enable/disable tab completer for sub-commands

# 4.Placeholders:
#   - {PLAYER} - player name who uses command

#  For other placeholders, use PlaceholderAPI plugin:
#   - https://www.spigotmc.org/resources/placeholderapi.6245/

# 4.Hex colors:
#   - To use HEX color, use &#HEXCODE (ex. &#DBC7FF)

# hex codes: https://htmlcolorcodes.com/
#---------------------------------------#
#               [Config]                #
#---------------------------------------#

default-message:
  permission: '&cYou do not have permission to use this command!'
  cooldown: '&cYou need to wait {0} seconds to use this command again!'
  arg: '&cYou need to provide more arguments!'

commands:
#  core: # <- command name (without /)
#    perm: 'core.admin' # <- when a player doesn't have permission, it will send a message default message
#    actions:
#      action-1:
#        type: 'replace' # <- replace, message, broadcast
#        action:
#          - 'essentials' # <- command to replace, when player use /core, it will replace to /essentials
#  info:
#    perm: 'info.admin' # <- permission to use this command
#    perm-message: '&cYou cannot use this command!' # <- message when player doesn't have permission
#    completer: true
#    #multi actions
#    actions:
#      action-1:
#        type: 'text'
#        action:
#          - '&#DBC7FFSended to all players!!' # <- to use HEX color, use &#HEXCODE
#      action-2:
#        type: 'broadcast'
#        action:
#          - '&aSended from {PLAYER}!'
#          - '&aHI ALL!'
  diamonds:
    cooldown: 5
    completer: true
    actions:
      action-1:
        type: 'text'
        action:
          - '&cUsage: /diamonds <amount>'
    routes:
      "<amount>":
        actions:
          action-1:
            type: 'text'
            action:
              - '&#DBC7FFDiamonds! {0}'
          action-2:
            type: 'server_command'
            action:
              - 'give {PLAYER} minecraft:diamond {0}'
  reward:
    completer: true
    actions:
      action-1:
        type: 'text'
        action:
          - '&aUsage: /reward give <player> <item> <amount>'
          - '&aUsage: /reward take <player> <item> <amount>'
    routes:
      "give <player> <item> <amount>":
        actions:
          action-1:
            type: 'server_command'
            action:
              - 'give {0} {1} {2}'

          action-2:
            type: 'broadcast'
            action:
              - '&a{PLAYER} gave {2}x {1} to {0}'

      "take <player> <item> <amount>":
        actions:
          action-1:
            type: 'server_command'
            action:
              - 'clear {0} {1} {2}'

          action-2:
            type: 'broadcast'
            action:
              - '&c{PLAYER} removed {2}x {1} from {0}'
