name: BetterCommands
version: '1.0.0'
main: pl.norbit.bettercommands.BetterCommands
api-version: '1.16'
author: Norbit4
website: 'https://n0rbit.pl'
softdepend:
  - PlaceholderAPI
commands:
  bettercommands:
    permission: 'bc.*'
    description: BetterCommands
    usage: /<command>
    aliases: [bc]
